-- ============================================================
-- 2026-07-05 03:00~03:20 이중집계로 잘못 지급된 업적 롤백
-- 대상: ACHV_ATTACK_TOTAL_* (공격횟수), ACHV_JOB_SKILL_* (직업스킬)
--        → 둘 다 BATTLE_JOB + BATTLE_LOG 이중집계 영향
-- 제외: ACHV_LIGHT_ITEM_*, ACHV_DARK_ITEM_* → INVENTORY 기반, 정상 지급
-- ============================================================

-- [1] 삭제 대상 확인
SELECT USER_NAME, CMD, SCORE, SCORE_EXT, INSERT_DATE
FROM TBOT_POINT_RANK
WHERE (CMD LIKE 'ACHV_ATTACK_TOTAL_%' OR CMD LIKE 'ACHV_JOB_SKILL_%')
  AND INSERT_DATE >= TO_DATE('2026-07-05 03:00', 'YYYY-MM-DD HH24:MI')
  AND INSERT_DATE <  TO_DATE('2026-07-05 03:20', 'YYYY-MM-DD HH24:MI')
ORDER BY USER_NAME, CMD;

-- [2] 유저별 건수 확인
SELECT USER_NAME, COUNT(*) AS CNT
FROM TBOT_POINT_RANK
WHERE (CMD LIKE 'ACHV_ATTACK_TOTAL_%' OR CMD LIKE 'ACHV_JOB_SKILL_%')
  AND INSERT_DATE >= TO_DATE('2026-07-05 03:00', 'YYYY-MM-DD HH24:MI')
  AND INSERT_DATE <  TO_DATE('2026-07-05 03:20', 'YYYY-MM-DD HH24:MI')
GROUP BY USER_NAME
ORDER BY USER_NAME;

-- [3] 확인 후 삭제
DELETE FROM TBOT_POINT_RANK
WHERE (CMD LIKE 'ACHV_ATTACK_TOTAL_%' OR CMD LIKE 'ACHV_JOB_SKILL_%')
  AND INSERT_DATE >= TO_DATE('2026-07-05 03:00', 'YYYY-MM-DD HH24:MI')
  AND INSERT_DATE <  TO_DATE('2026-07-05 03:20', 'YYYY-MM-DD HH24:MI');

COMMIT;
