-- 가방 아이템 ITEM_TYPE을 BAG_SHOP으로 변경
UPDATE TBOT_POINT_NEW_ITEM SET ITEM_TYPE = 'BAG_SHOP' WHERE ITEM_ID IN (91, 92, 93);
COMMIT;
SELECT ITEM_ID, ITEM_NAME, ITEM_TYPE FROM TBOT_POINT_NEW_ITEM WHERE ITEM_ID IN (91,92,93);
EXIT
