SET PAGESIZE 20
SET LINESIZE 120

-- REMARK 컬럼 데이터 확인
SELECT COUNT(*) AS TOTAL, COUNT(REMARK) AS HAS_REMARK
  FROM TBOT_POINT_RANK_OLD;

-- 샘플 확인
SELECT REMARK FROM TBOT_POINT_RANK_OLD WHERE REMARK IS NOT NULL AND ROWNUM <= 5;

-- REMARK 컬럼 DROP (데이터 없거나 불필요하면 실행)
ALTER TABLE TBOT_POINT_RANK_OLD DROP COLUMN REMARK;

-- 최종 검증
SELECT TABLE_NAME, COLUMN_NAME, COLUMN_ID, DATA_TYPE, DATA_PRECISION, DATA_SCALE
  FROM USER_TAB_COLUMNS
 WHERE TABLE_NAME IN ('TBOT_POINT_RANK', 'TBOT_POINT_RANK_OLD')
 ORDER BY TABLE_NAME, COLUMN_ID;

SELECT * FROM TBOT_POINT_RANK       WHERE ROWNUM <= 1;
SELECT * FROM TBOT_POINT_RANK_OLD   WHERE ROWNUM <= 1;
SELECT * FROM TBOT_POINT_RANK UNION ALL SELECT * FROM TBOT_POINT_RANK_OLD WHERE ROWNUM <= 1;

EXIT
