-- TBOT_MACRO_CONFIG 테이블/컬럼 코멘트 재설정 (한글 깨짐 수정)
COMMENT ON TABLE  TBOT_MACRO_CONFIG              IS '유저별 매크로 감지 임계값 (수동 조정 가능)';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.USER_NAME    IS '유저명';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.HOURLY_LIMIT IS '1시간 기준 허용 공격 횟수 (기본 20)';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.NIGHT_MULTI  IS '야간 임계값 배율 (기본 0.5, 야간한도=HOURLY_LIMIT x 0.5)';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.MEMO         IS '관리자 메모';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.INSERT_DATE  IS '최초 생성일 (매크로 최초 탐지 시점)';
COMMENT ON COLUMN TBOT_MACRO_CONFIG.UPDATE_DATE  IS '최종 수정일';
