-- ============================================================
-- S4 업적 개편 마이그레이션
-- 낚시대: ALL_KIND_GRADE(도감완성) → ROD_UNLOCK
-- 찌:    TOTAL_FISHING_COUNT(누적 횟수) → BOBBER_UNLOCK
-- ============================================================

-- 1. FIRST_CATCH_GRADE 업적: 보상 제거 (달성 표시만 유지)
UPDATE TBOT_S4_ACHIEVEMENT
   SET REWARD_TYPE = NULL, REWARD_GRADE = NULL
 WHERE ACH_TYPE = 'FIRST_CATCH_GRADE';

-- 2. 기존 도감완성 업적을 BOBBER → ROD_UNLOCK으로 변경
--    ACH_ID 2: ★1 도감완성 → 고급낚시대
UPDATE TBOT_S4_ACHIEVEMENT
   SET ACH_NAME = '★1 도감 완성!', REWARD_TYPE = 'ROD_UNLOCK', REWARD_GRADE = 2
 WHERE ACH_ID = 2;

--    ACH_ID 3: ★2 도감완성 → 희귀낚시대
UPDATE TBOT_S4_ACHIEVEMENT
   SET ACH_NAME = '★2 도감 완성!', REWARD_TYPE = 'ROD_UNLOCK', REWARD_GRADE = 3
 WHERE ACH_ID = 3;

--    ACH_ID 4: ★3 도감완성 → 영웅낚시대
UPDATE TBOT_S4_ACHIEVEMENT
   SET ACH_NAME = '★3 도감 완성!', REWARD_TYPE = 'ROD_UNLOCK', REWARD_GRADE = 4
 WHERE ACH_ID = 4;

-- 3. 신규 업적: 누적 낚시 횟수 → 찌 해금
--    (ACH_ID 8~10: 기존에 없으면 INSERT, 있으면 UPDATE)
MERGE INTO TBOT_S4_ACHIEVEMENT a
USING (SELECT 8 AS ACH_ID FROM DUAL) s ON (a.ACH_ID = s.ACH_ID)
WHEN MATCHED THEN
    UPDATE SET ACH_NAME = '낚시 10회 달성!', ACH_DESC = '낚시를 10번 완료했다!',
               ACH_TYPE = 'TOTAL_FISHING_COUNT', ACH_PARAM = '10',
               REWARD_TYPE = 'BOBBER_UNLOCK', REWARD_GRADE = 2
WHEN NOT MATCHED THEN
    INSERT (ACH_ID, ACH_NAME, ACH_DESC, ACH_TYPE, ACH_PARAM, REWARD_TYPE, REWARD_GRADE)
    VALUES (8, '낚시 10회 달성!', '낚시를 10번 완료했다!', 'TOTAL_FISHING_COUNT', '10', 'BOBBER_UNLOCK', 2);

MERGE INTO TBOT_S4_ACHIEVEMENT a
USING (SELECT 9 AS ACH_ID FROM DUAL) s ON (a.ACH_ID = s.ACH_ID)
WHEN MATCHED THEN
    UPDATE SET ACH_NAME = '낚시 30회 달성!', ACH_DESC = '낚시를 30번 완료했다!',
               ACH_TYPE = 'TOTAL_FISHING_COUNT', ACH_PARAM = '30',
               REWARD_TYPE = 'BOBBER_UNLOCK', REWARD_GRADE = 3
WHEN NOT MATCHED THEN
    INSERT (ACH_ID, ACH_NAME, ACH_DESC, ACH_TYPE, ACH_PARAM, REWARD_TYPE, REWARD_GRADE)
    VALUES (9, '낚시 30회 달성!', '낚시를 30번 완료했다!', 'TOTAL_FISHING_COUNT', '30', 'BOBBER_UNLOCK', 3);

MERGE INTO TBOT_S4_ACHIEVEMENT a
USING (SELECT 10 AS ACH_ID FROM DUAL) s ON (a.ACH_ID = s.ACH_ID)
WHEN MATCHED THEN
    UPDATE SET ACH_NAME = '낚시 60회 달성!', ACH_DESC = '낚시를 60번 완료했다!',
               ACH_TYPE = 'TOTAL_FISHING_COUNT', ACH_PARAM = '60',
               REWARD_TYPE = 'BOBBER_UNLOCK', REWARD_GRADE = 4
WHEN NOT MATCHED THEN
    INSERT (ACH_ID, ACH_NAME, ACH_DESC, ACH_TYPE, ACH_PARAM, REWARD_TYPE, REWARD_GRADE)
    VALUES (10, '낚시 60회 달성!', '낚시를 60번 완료했다!', 'TOTAL_FISHING_COUNT', '60', 'BOBBER_UNLOCK', 4);

-- ============================================================
-- 기존 유저 보정
-- ============================================================

-- 4. 잘못 적재된 장비 보정
--    도감완성 업적(ACH_ID 2,3,4) 달성자 → 낚시대 등급 자동 보정
--    (ROD_GRADE가 ACH의 REWARD_GRADE보다 낮으면 올려줌)
UPDATE TBOT_S4_USER_EQUIP e
   SET e.ROD_GRADE = (
       SELECT MAX(a.REWARD_GRADE)
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'ROD_UNLOCK'
   )
 WHERE EXISTS (
       SELECT 1
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'ROD_UNLOCK'
   )
   AND e.ROD_GRADE < (
       SELECT MAX(a.REWARD_GRADE)
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'ROD_UNLOCK'
   );

-- 5. 누적 낚시 횟수 기준으로 신규 업적(ACH_ID 8,9,10) 소급 부여
--    10회 달성자: 10번째 낚시 날짜로 CLEAR_DATE 소급
INSERT INTO TBOT_S4_USER_ACH (USER_NAME, ACH_ID, CLEAR_DATE)
SELECT USER_NAME, 8, FISHING_DATE
  FROM (
       SELECT USER_NAME, FISHING_DATE,
              ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY FISHING_DATE) AS RN
         FROM TBOT_S4_FISHING_LOG
       )
 WHERE RN = 10
   AND USER_NAME NOT IN (SELECT USER_NAME FROM TBOT_S4_USER_ACH WHERE ACH_ID = 8);

--    30회 달성자
INSERT INTO TBOT_S4_USER_ACH (USER_NAME, ACH_ID, CLEAR_DATE)
SELECT USER_NAME, 9, FISHING_DATE
  FROM (
       SELECT USER_NAME, FISHING_DATE,
              ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY FISHING_DATE) AS RN
         FROM TBOT_S4_FISHING_LOG
       )
 WHERE RN = 30
   AND USER_NAME NOT IN (SELECT USER_NAME FROM TBOT_S4_USER_ACH WHERE ACH_ID = 9);

--    60회 달성자
INSERT INTO TBOT_S4_USER_ACH (USER_NAME, ACH_ID, CLEAR_DATE)
SELECT USER_NAME, 10, FISHING_DATE
  FROM (
       SELECT USER_NAME, FISHING_DATE,
              ROW_NUMBER() OVER (PARTITION BY USER_NAME ORDER BY FISHING_DATE) AS RN
         FROM TBOT_S4_FISHING_LOG
       )
 WHERE RN = 60
   AND USER_NAME NOT IN (SELECT USER_NAME FROM TBOT_S4_USER_ACH WHERE ACH_ID = 10);

-- 6. 찌 등급도 보정 (업적 달성자인데 장비가 낮으면)
UPDATE TBOT_S4_USER_EQUIP e
   SET e.BOBBER_GRADE = (
       SELECT MAX(a.REWARD_GRADE)
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'BOBBER_UNLOCK'
   )
 WHERE EXISTS (
       SELECT 1
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'BOBBER_UNLOCK'
   )
   AND e.BOBBER_GRADE < (
       SELECT MAX(a.REWARD_GRADE)
         FROM TBOT_S4_USER_ACH ua
         JOIN TBOT_S4_ACHIEVEMENT a ON ua.ACH_ID = a.ACH_ID
        WHERE ua.USER_NAME = e.USER_NAME
          AND a.REWARD_TYPE = 'BOBBER_UNLOCK'
   );

COMMIT;
