-- S4 카카오 로그인 회원 테이블
CREATE TABLE TBOT_S4_MEMBER (
    KAKAO_ID    VARCHAR2(50)  NOT NULL PRIMARY KEY,
    USER_NAME   VARCHAR2(100) NOT NULL,
    NICKNAME    VARCHAR2(100),
    REG_DATE    DATE          DEFAULT SYSDATE,
    LAST_LOGIN  DATE          DEFAULT SYSDATE
);

CREATE UNIQUE INDEX IDX_S4_MEMBER_USERNAME ON TBOT_S4_MEMBER (USER_NAME);
