-- ============================================================
-- Season 5 - Full balance rework, phase 1: NEW tables only (2026-09-21).
--
-- Goal (user request 2026-09-20/21): "make one fight last longer" (normal
-- monster ~4-5 party rounds to kill, boss ~10+ rounds), and replace the
-- current block-jump monster curve (TBOT_S5_MONSTER_INFO, one row per
-- 10-floor block with huge multiplicative jumps at block boundaries) with a
-- single continuous LINEAR function of floor across 1-100. Companion/equip
-- base-stat curves are also smoothed (converted from hand-tuned, slightly
-- irregular grade-to-grade ratios into constant-ratio geometric curves that
-- match the old grade1 and grade6/7 endpoints exactly).
--
-- IMPORTANT -- STATUS: SOURCE ONLY, NOT YET APPLIED (per explicit request
-- "commit/push the source first, review and actual cutover later"):
--   1) This script has NOT been run against the live DB yet.
--   2) BotS5ServiceImpl.java has NOT been changed to read these tables --
--      combatPower/computeEffectiveStat/monster lookup all still use the
--      old TBOT_S5_MONSTER_INFO table and the old hardcoded Java constant
--      arrays (GRADE_BASE/JOB_MULT/EQUIP_BONUS/LIMIT_BREAK_PCT). Nothing
--      about live gameplay changes until BOTH this script is executed AND
--      a follow-up code change wires the read path to these new tables.
--   3) Old table/constants are left completely untouched (rollback-safe).
--
-- Design derivation (full detail + AS-IS/TO-BE tables): see
-- S5_TOWER_DESIGN.md, "[2026-09-21] 밸런스 전면 재설계" section, and the
-- approved plan at .claude/plans/linear-mapping-wall.md. Short version:
--   - Pulled real party ATK/HP/DEF for 16 actual progressing users (11~89F)
--     using the exact computeEffectiveStat() formula.
--   - Derived a per-floor "ideal" monster HP/ATK/DEF from the combat math
--     (party dmg/round = SUM_ATK*avgRoll - 3*monsterDEF; monster HP sized
--     so a normal fight takes ~4.5 rounds, a boss fight ~11 rounds).
--   - Fit ONE straight line through that ideal curve (anchored at floor=1
--     to avoid the negative-value artifact a naive whole-range OLS produces,
--     since real player power grows convexly while monster stats must not).
--
-- Final linear formulas (floor = absolute floor number, 1-100):
--   normal HP  = 420    + 1304 * (floor-1)
--   normal ATK = 6      + 1.85 * (floor-1)
--   normal DEF = 17     + 52   * (floor-1)
--   boss   HP  = 1026   + 3187 * (floor-1)
--   boss   ATK = 7      + 2.35 * (floor-1)
--   boss   DEF = 20     + 62   * (floor-1)
--
-- Judgment calls made without further user confirmation (flagged for
-- review before actual cutover): target rounds-to-kill K=4.5 (normal) /
-- K=11 (boss); monster DEF sized to absorb ~35% of a party member's average
-- per-hit damage; monster ATK sized to deal ~15%(normal)/20%(boss) of a
-- companion's average HP per hit; boss DEF/ATK slope set to 1.2x normal's.
--
-- ASCII-only file (values only, no Korean literals), safe to review/run.
-- ============================================================

CREATE TABLE TBOT_S5_MONSTER_INFO_V2 (
    FLOOR      NUMBER PRIMARY KEY,
    BOSS_YN    CHAR(1) DEFAULT 'N' NOT NULL,
    HP_VALUE   NUMBER NOT NULL,
    ATK_VALUE  NUMBER NOT NULL,
    DEF_VALUE  NUMBER NOT NULL
);
COMMENT ON TABLE TBOT_S5_MONSTER_INFO_V2 IS 'v2 balance rework: one row per hunting/boss floor (1-99, village floors X0 excluded), replaces block-based TBOT_S5_MONSTER_INFO. NOT YET WIRED TO LIVE CODE.';

CREATE TABLE TBOT_S5_GRADE_BASE_V2 (
    GRADE      NUMBER PRIMARY KEY,
    HP_VALUE   NUMBER NOT NULL,
    ATK_VALUE  NUMBER NOT NULL,
    DEF_VALUE  NUMBER NOT NULL
);
COMMENT ON TABLE TBOT_S5_GRADE_BASE_V2 IS 'v2 balance rework: companion base stat by star-grade (1-6), constant-ratio geometric curve anchored to current live grade1/grade6 values. Replaces Java constant GRADE_BASE. NOT YET WIRED TO LIVE CODE.';

CREATE TABLE TBOT_S5_EQUIP_BONUS_V2 (
    GRADE        NUMBER PRIMARY KEY,
    HELM_FLAT    NUMBER NOT NULL,
    HELM_PCT     NUMBER NOT NULL,
    WEAPON_FLAT  NUMBER NOT NULL,
    WEAPON_PCT   NUMBER NOT NULL,
    ARMOR_FLAT   NUMBER NOT NULL,
    ARMOR_PCT    NUMBER NOT NULL
);
COMMENT ON TABLE TBOT_S5_EQUIP_BONUS_V2 IS 'v2 balance rework: equipment grade bonus (1-7, 7=legendary), constant-ratio geometric curve anchored to current live grade1/grade7 values. Replaces Java constant EQUIP_BONUS. NOT YET WIRED TO LIVE CODE.';

CREATE TABLE TBOT_S5_LIMIT_BREAK_V2 (
    LEVEL  NUMBER PRIMARY KEY,
    PCT    NUMBER NOT NULL
);
COMMENT ON TABLE TBOT_S5_LIMIT_BREAK_V2 IS 'v2 balance rework: limit-break stat multiplier by level (0-6). Values unchanged from current live LIMIT_BREAK_PCT (already a clean +30%/level line) -- just table-ified for DB-driven tuning. NOT YET WIRED TO LIVE CODE.';

-- ---------------- TBOT_S5_MONSTER_INFO_V2 (90 rows: 80 hunting + 10 boss floors) ----------------
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (1, 'N', 420, 6, 17);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (2, 'N', 1724, 8, 69);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (3, 'N', 3028, 10, 121);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (4, 'N', 4332, 12, 173);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (5, 'N', 5636, 13, 225);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (6, 'N', 6940, 15, 277);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (7, 'N', 8244, 17, 329);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (8, 'N', 9548, 19, 381);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (9, 'Y', 26522, 26, 516);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (11, 'N', 13460, 25, 537);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (12, 'N', 14764, 26, 589);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (13, 'N', 16068, 28, 641);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (14, 'N', 17372, 30, 693);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (15, 'N', 18676, 32, 745);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (16, 'N', 19980, 34, 797);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (17, 'N', 21284, 36, 849);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (18, 'N', 22588, 37, 901);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (19, 'Y', 58392, 49, 1136);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (21, 'N', 26500, 43, 1057);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (22, 'N', 27804, 45, 1109);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (23, 'N', 29108, 47, 1161);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (24, 'N', 30412, 49, 1213);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (25, 'N', 31716, 50, 1265);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (26, 'N', 33020, 52, 1317);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (27, 'N', 34324, 54, 1369);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (28, 'N', 35628, 56, 1421);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (29, 'Y', 90262, 73, 1756);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (31, 'N', 39540, 62, 1577);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (32, 'N', 40844, 63, 1629);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (33, 'N', 42148, 65, 1681);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (34, 'N', 43452, 67, 1733);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (35, 'N', 44756, 69, 1785);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (36, 'N', 46060, 71, 1837);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (37, 'N', 47364, 73, 1889);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (38, 'N', 48668, 74, 1941);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (39, 'Y', 122132, 96, 2376);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (41, 'N', 52580, 80, 2097);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (42, 'N', 53884, 82, 2149);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (43, 'N', 55188, 84, 2201);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (44, 'N', 56492, 86, 2253);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (45, 'N', 57796, 87, 2305);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (46, 'N', 59100, 89, 2357);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (47, 'N', 60404, 91, 2409);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (48, 'N', 61708, 93, 2461);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (49, 'Y', 154002, 120, 2996);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (51, 'N', 65620, 99, 2617);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (52, 'N', 66924, 100, 2669);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (53, 'N', 68228, 102, 2721);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (54, 'N', 69532, 104, 2773);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (55, 'N', 70836, 106, 2825);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (56, 'N', 72140, 108, 2877);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (57, 'N', 73444, 110, 2929);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (58, 'N', 74748, 111, 2981);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (59, 'Y', 185872, 143, 3616);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (61, 'N', 78660, 117, 3137);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (62, 'N', 79964, 119, 3189);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (63, 'N', 81268, 121, 3241);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (64, 'N', 82572, 123, 3293);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (65, 'N', 83876, 124, 3345);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (66, 'N', 85180, 126, 3397);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (67, 'N', 86484, 128, 3449);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (68, 'N', 87788, 130, 3501);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (69, 'Y', 217742, 167, 4236);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (71, 'N', 91700, 136, 3657);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (72, 'N', 93004, 137, 3709);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (73, 'N', 94308, 139, 3761);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (74, 'N', 95612, 141, 3813);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (75, 'N', 96916, 143, 3865);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (76, 'N', 98220, 145, 3917);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (77, 'N', 99524, 147, 3969);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (78, 'N', 100828, 148, 4021);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (79, 'Y', 249612, 190, 4856);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (81, 'N', 104740, 154, 4177);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (82, 'N', 106044, 156, 4229);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (83, 'N', 107348, 158, 4281);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (84, 'N', 108652, 160, 4333);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (85, 'N', 109956, 161, 4385);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (86, 'N', 111260, 163, 4437);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (87, 'N', 112564, 165, 4489);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (88, 'N', 113868, 167, 4541);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (89, 'Y', 281482, 214, 5476);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (91, 'N', 117780, 173, 4697);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (92, 'N', 119084, 174, 4749);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (93, 'N', 120388, 176, 4801);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (94, 'N', 121692, 178, 4853);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (95, 'N', 122996, 180, 4905);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (96, 'N', 124300, 182, 4957);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (97, 'N', 125604, 184, 5009);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (98, 'N', 126908, 185, 5061);
INSERT INTO TBOT_S5_MONSTER_INFO_V2 (FLOOR, BOSS_YN, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (99, 'Y', 313352, 237, 6096);

-- ---------------- TBOT_S5_GRADE_BASE_V2 (6 rows) ----------------
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (1, 100, 10, 5);
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (2, 158, 16, 8);
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (3, 250, 25, 13);
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (4, 395, 39, 21);
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (5, 625, 62, 35);
INSERT INTO TBOT_S5_GRADE_BASE_V2 (GRADE, HP_VALUE, ATK_VALUE, DEF_VALUE) VALUES (6, 988, 98, 56);

-- ---------------- TBOT_S5_EQUIP_BONUS_V2 (7 rows, 7=legendary) ----------------
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (1, 30, 0.050, 5, 0.050, 3, 0.050);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (2, 57, 0.072, 10, 0.072, 6, 0.072);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (3, 109, 0.104, 19, 0.104, 11, 0.104);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (4, 209, 0.150, 37, 0.150, 21, 0.150);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (5, 398, 0.216, 71, 0.216, 40, 0.216);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (6, 760, 0.312, 139, 0.312, 76, 0.312);
INSERT INTO TBOT_S5_EQUIP_BONUS_V2 (GRADE, HELM_FLAT, HELM_PCT, WEAPON_FLAT, WEAPON_PCT, ARMOR_FLAT, ARMOR_PCT) VALUES (7, 1450, 0.450, 270, 0.450, 145, 0.450);

-- ---------------- TBOT_S5_LIMIT_BREAK_V2 (7 rows, unchanged values) ----------------
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (0, 0.00);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (1, 0.30);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (2, 0.60);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (3, 0.90);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (4, 1.20);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (5, 1.50);
INSERT INTO TBOT_S5_LIMIT_BREAK_V2 (LEVEL, PCT) VALUES (6, 1.80);

COMMIT;

-- Verification (row counts only, no live-code impact either way):
SELECT COUNT(*) AS MONSTER_V2_ROWS FROM TBOT_S5_MONSTER_INFO_V2;
SELECT COUNT(*) AS GRADE_BASE_V2_ROWS FROM TBOT_S5_GRADE_BASE_V2;
SELECT COUNT(*) AS EQUIP_BONUS_V2_ROWS FROM TBOT_S5_EQUIP_BONUS_V2;
SELECT COUNT(*) AS LIMIT_BREAK_V2_ROWS FROM TBOT_S5_LIMIT_BREAK_V2;
EXIT;
