-- ============================================================
-- Season 5 - companion name pool narrowed to 3 names per job (was one
-- shared pool of 24 names across all jobs -- felt like "too many names
-- appearing"). This migrates EXISTING TBOT_S5_USER_COMPANION rows whose
-- NAME is not one of the new 3-per-job names to one of those 3, picked
-- deterministically by MOD(COMPANION_ID, 3) so re-running is idempotent
-- (rows already on a valid name for their job are left untouched).
--
-- No separate "companion name master" table exists -- NAME is just a
-- plain column on TBOT_S5_USER_COMPANION, populated at gacha-pull time
-- from a Java constant (NAME_POOL_BY_JOB in BotS5ServiceImpl.java).
--
-- Korean literals written as CP949(=KO16MSWIN949) hex via HEXTORAW per
-- CLAUDE.md policy (sqlplus round-trip alone is not trustworthy -- see
-- "DB 스크립트 실행 (sqlplus)" section). ASCII-only file.
--   WARRIOR: 리쿠(B8AEC4ED) 소우타(BCD2BFECC5B8) 슌(9A9C)
--   MAGE:    유키(C0AFC5B0) 아오이(BEC6BFC0C0CC) 이츠키(C0CCC3F7C5B0)
--   ROGUE:   카이토(C4ABC0CCC5E4) 료(B7E1) 츠바사(C3F7B9D9BBE7)
--   ARCHER:  소라(BCD2B6F3) 유토(C0AFC5E4) 나나(B3AAB3AA)
--   PRIEST:  사쿠라(BBE7C4EDB6F3) 히나(C8F7B3AA) 유이(C0AFC0CC)
-- ============================================================

UPDATE TBOT_S5_USER_COMPANION
SET NAME = UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(
    CASE MOD(COMPANION_ID, 3) WHEN 0 THEN 'B8AEC4ED' WHEN 1 THEN 'BCD2BFECC5B8' ELSE '9A9C' END))
WHERE CLASS = 'WARRIOR'
  AND NAME NOT IN (
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8AEC4ED')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCD2BFECC5B8')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('9A9C')));

UPDATE TBOT_S5_USER_COMPANION
SET NAME = UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(
    CASE MOD(COMPANION_ID, 3) WHEN 0 THEN 'C0AFC5B0' WHEN 1 THEN 'BEC6BFC0C0CC' ELSE 'C0CCC3F7C5B0' END))
WHERE CLASS = 'MAGE'
  AND NAME NOT IN (
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFC5B0')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6BFC0C0CC')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0CCC3F7C5B0')));

UPDATE TBOT_S5_USER_COMPANION
SET NAME = UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(
    CASE MOD(COMPANION_ID, 3) WHEN 0 THEN 'C4ABC0CCC5E4' WHEN 1 THEN 'B7E1' ELSE 'C3F7B9D9BBE7' END))
WHERE CLASS = 'ROGUE'
  AND NAME NOT IN (
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4ABC0CCC5E4')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B7E1')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C3F7B9D9BBE7')));

UPDATE TBOT_S5_USER_COMPANION
SET NAME = UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(
    CASE MOD(COMPANION_ID, 3) WHEN 0 THEN 'BCD2B6F3' WHEN 1 THEN 'C0AFC5E4' ELSE 'B3AAB3AA' END))
WHERE CLASS = 'ARCHER'
  AND NAME NOT IN (
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCD2B6F3')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFC5E4')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B3AAB3AA')));

UPDATE TBOT_S5_USER_COMPANION
SET NAME = UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW(
    CASE MOD(COMPANION_ID, 3) WHEN 0 THEN 'BBE7C4EDB6F3' WHEN 1 THEN 'C8F7B3AA' ELSE 'C0AFC0CC' END))
WHERE CLASS = 'PRIEST'
  AND NAME NOT IN (
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BBE7C4EDB6F3')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C8F7B3AA')),
    UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFC0CC')));

COMMIT;

-- 검증: 클래스별 이름 분포가 3종으로만 모였는지 + 실제 저장 바이트(hex)가 의도한 값과 일치하는지 확인
SELECT CLASS, NAME, RAWTOHEX(UTL_RAW.CAST_TO_RAW(NAME)) AS NAME_HEX, COUNT(*) AS CNT
FROM TBOT_S5_USER_COMPANION
GROUP BY CLASS, NAME
ORDER BY CLASS, NAME;

EXIT;
