-- ============================================================
-- Season 5 - legendary robe #4 (2026-09-29): MAGE+PRIEST robe (ROBE/ARMOR),
-- START_BARRIER: wearer starts each combat with a one-time invulnerability
-- ward (next hit fully negated). Name = "enigma" (Korean word, CP949 hex).
-- EFFECT_PARAM1 unused (NOT NULL column -> 1). Idempotent.
-- ============================================================
DECLARE
    v_cnt NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_cnt FROM TBOT_S5_LEGENDARY_MASTER WHERE LEGENDARY_ID = 4;
    IF v_cnt = 0 THEN
        INSERT INTO TBOT_S5_LEGENDARY_MASTER (LEGENDARY_ID, CLASS, PART, ITEM_NAME, EFFECT_TYPE, EFFECT_PARAM1, EFFECT_PARAM2, FLAVOR_TEXT)
        VALUES (4, 'ROBE', 'ARMOR',
            UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCF6BCF6B2B2B3A2')),
            'START_BARRIER', 1, 0,
            UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C1A4C3BCB8A620BECB20BCF620BEF8B4C220B7CEBAEA2E20C0D4B4C220BCF8B0A320B9ABC0FBC0C720C0E5B8B7C0CC20C6EEC3C4C1F8B4D9')));
    END IF;
END;
/

COMMIT;

SELECT LEGENDARY_ID, CLASS, PART, EFFECT_TYPE, EFFECT_PARAM1, RAWTOHEX(UTL_RAW.CAST_TO_RAW(ITEM_NAME)) AS NAME_HEX
FROM TBOT_S5_LEGENDARY_MASTER ORDER BY LEGENDARY_ID;

-- Sanity check of the shared query change (selectEquipByCompanion JOIN) -- must parse/run.
SELECT COUNT(*) AS JOIN_OK FROM (
  SELECT e.EQUIP_ID, e.PART, e.GRADE, e.LEGENDARY_ID,
         lm.EFFECT_TYPE AS LEGENDARY_EFFECT_TYPE, lm.EFFECT_PARAM1 AS LEGENDARY_EFFECT_PARAM1,
         lm.ITEM_NAME AS LEGENDARY_ITEM_NAME
    FROM TBOT_S5_USER_EQUIP e
    LEFT JOIN TBOT_S5_LEGENDARY_MASTER lm ON lm.LEGENDARY_ID = e.LEGENDARY_ID
   WHERE e.EQUIPPED_COMPANION_ID = 157);
