-- ============================================================
-- Season 5 - live DB migration: split companion name pool by GRADE (star tier).
--
-- Root cause of the "already-owned name pulled again at a higher grade just
-- evaporates" bug (confirmed live case reported by a user: owned a GRADE=2
-- ARCHER companion, pulled a GRADE=3 ARCHER that happened to roll the exact
-- same name, got refunded 20% PP instead of a new companion): names used to
-- be shared across ALL grades (3 names per job, grade-independent), so the
-- same name could appear at two different grades and collide with the "same
-- job+name = duplicate" check. The application code (BotS5ServiceImpl) now
-- uses NAME_POOL_BY_JOB_GRADE -- grade 1 keeps the original 15 names, grades
-- 2-6 get brand new non-overlapping names (2x3 + 3x3 + 4x2 + 5x1 + 6x1 = 13
-- per job, 65 total) -- so a name now always implies its grade and this class
-- of bug can no longer happen going forward.
--
-- This script only fixes EXISTING data: every companion currently at GRADE>=2
-- still carries an old grade-independent name (one of the original 15 names,
-- which are now GRADE=1-only) and needs to be renamed to a name from its own
-- grade's new pool. GRADE=1 rows are untouched (grade 1
-- pool is unchanged). Names are Korean but this file is pure ASCII -- every
-- literal goes in as CP949 (KO16MSWIN949) bytes via HEXTORAW per CLAUDE.md's
-- encoding rule, never as a literal Korean character in the .sql file itself.
--
-- Assignment rule: for each (USER_NAME, CLASS, GRADE) group, existing rows are
-- numbered by COMPANION_ID and cycled through that grade's name pool (MOD),
-- so within one user's own roster the new names differ as long as they don't
-- already own more same-class-same-grade companions than that tier's pool
-- size (checked against live data before writing this script -- max 2 seen,
-- well under the smallest pool size of 3 for grades 2-3; grades 4-6 have no
-- existing rows at all yet). Reuse of a name across DIFFERENT users is fine
-- and expected (same as the original shared-pool design).
--
-- Safe to re-run (idempotent: recomputes the same deterministic assignment
-- each time, no accumulating side effects).
-- ============================================================

MERGE INTO TBOT_S5_USER_COMPANION C
USING (
    SELECT R.COMPANION_ID, NP.NM AS NEW_NAME
    FROM (
        SELECT COMPANION_ID, CLASS, GRADE,
               MOD(
                   ROW_NUMBER() OVER (PARTITION BY USER_NAME, CLASS, GRADE ORDER BY COMPANION_ID) - 1,
                   CASE GRADE WHEN 4 THEN 2 WHEN 5 THEN 1 WHEN 6 THEN 1 ELSE 3 END
               ) AS IDX
        FROM TBOT_S5_USER_COMPANION
        WHERE GRADE >= 2
    ) R
    JOIN (
        -- name pool for grades 2-6, generated from NAME_POOL_BY_JOB_GRADE (grade 1 pool unchanged, not included here)
        SELECT 'WARRIOR' CLASS, 2 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4CBB0ED')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 2 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B4D9C0CCC5B0')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 2 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFB8B6')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 3 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C7CFBEDFC5E4')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 3 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4DAC5B8B7CE')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 3 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C1F8')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 4 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B7BBC1F6')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 4 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6C3F7BDC3')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 5 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C3F7BFE4BDC3')) NM FROM DUAL UNION ALL
        SELECT 'WARRIOR' CLASS, 6 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B0EDBFECC5B0')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 2 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B9CCC0AF')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 2 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8AEBBE7')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 2 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B3AABFC0')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 3 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BBE7BEDF')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 3 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8B6C0CC')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 3 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFB3AA')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 4 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8AEBFC0')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 4 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4ABB3AA')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 5 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B9CCC4DAC5E4')) NM FROM DUAL UNION ALL
        SELECT 'MAGE' CLASS, 6 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCBCB6F3')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 2 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BDC5C1F6')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 2 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C5B8C4EDBEDF')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 2 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B0D5C1F6')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 3 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B7B9C0CC')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 3 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6C5B0B6F3')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 3 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCD2B8B6')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 4 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFC0CCC5E4')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 4 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4ABB0D4B7CEBFEC')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 5 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B3AAB1E2')) NM FROM DUAL UNION ALL
        SELECT 'ROGUE' CLASS, 6 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEDFC5E4')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 2 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6BEDF')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 2 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B9CCBBE7C5B0')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 2 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0AFC1EEC5B0')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 3 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8AEC4DA')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 3 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8B6C0AF')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 3 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C7CFB7E7C4AB')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 4 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BCBCB8AEB3AA')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 4 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C3F7C5B0B9CC')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 5 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BDBAC1EEB3D7')) NM FROM DUAL UNION ALL
        SELECT 'ARCHER' CLASS, 6 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6B8B6C3F7')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 2 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B8F0B8F0C4AB')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 2 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C0CCBFC0B8AE')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 2 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BDC3BFC2')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 3 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B3EBC1B6B9CC')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 3 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6BBE7C8F7')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 3 GRADE, 2 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B7BBB0D4')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 4 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('C4DAC7CFB7E7')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 4 GRADE, 1 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('B9CCB7B9C0CC')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 5 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BDBAC0CCB7BB')) NM FROM DUAL UNION ALL
        SELECT 'PRIEST' CLASS, 6 GRADE, 0 IDX, UTL_RAW.CAST_TO_VARCHAR2(HEXTORAW('BEC6B8B6B3D7')) NM FROM DUAL
    ) NP ON (NP.CLASS = R.CLASS AND NP.GRADE = R.GRADE AND NP.IDX = R.IDX)
) SRC
ON (C.COMPANION_ID = SRC.COMPANION_ID)
WHEN MATCHED THEN UPDATE SET C.NAME = SRC.NEW_NAME;

COMMIT;

-- Verify: no GRADE>=2 companion should still carry a GRADE=1-only name after this.
SELECT CLASS, GRADE, NAME, COUNT(*) CNT
FROM TBOT_S5_USER_COMPANION
WHERE GRADE >= 2
GROUP BY CLASS, GRADE, NAME
ORDER BY CLASS, GRADE, NAME;

EXIT;
