-- ============================================================
-- Season 5 - live DB migration: rename existing 'STAIRS' tiles to 'STAIRS_UP'.
--
-- The single STAIRS tile type was split into STAIRS_UP/STAIRS_DOWN (2 tiles
-- per floor going forward, generated by ensureUserBoard() for newly (re)made
-- boards -- boards regenerate automatically whenever a player returns to
-- village). This script only patches ALREADY-GENERATED per-user boards
-- (TBOT_S5_USER_TILE_MASTER) still sitting on the old single-tile scheme, so
-- players mid-expedition on those boards don't lose the ability to unlock
-- the next floor (the STAIRS_UP case is what updates MAX_FLOOR_REACHED --
-- without this rename their old 'STAIRS' tile would match no switch case at
-- all and silently do nothing if stepped on).
--
-- This does NOT add a STAIRS_DOWN tile to already-generated boards (that
-- would require picking a safe tile to convert without disturbing current
-- position/discovered-tile counts) -- those boards simply won't support the
-- "land exactly on stairs" directional-arrival feature until the player
-- next returns to village and the board regenerates fresh (with both tiles).
-- Existing player progress/position/discovered-tiles are untouched here.
--
-- ASCII-only file, safe to re-run (WHERE clause makes it a no-op after the
-- first successful run).
-- ============================================================

UPDATE TBOT_S5_USER_TILE_MASTER
SET TILE_TYPE = 'STAIRS_UP'
WHERE TILE_TYPE = 'STAIRS';

COMMIT;

SELECT TILE_TYPE, COUNT(*) FROM TBOT_S5_USER_TILE_MASTER GROUP BY TILE_TYPE ORDER BY TILE_TYPE;
EXIT;
