-- TBOT_POINT_NEW_RANK: 유저당 1행, SP/GP 현재잔액 및 최대값 저장
-- insertPointRank / insertGpRecord 시 MERGE로 항상 최신 상태 유지
CREATE TABLE TBOT_POINT_NEW_RANK (
    USER_NAME   VARCHAR2(100)  NOT NULL,
    CUR_SP      NUMBER(20, 4)  DEFAULT 0  NOT NULL,
    CUR_SP_EXT  VARCHAR2(10)   DEFAULT '' ,
    MAX_SP      NUMBER(20, 4)  DEFAULT 0  NOT NULL,
    MAX_SP_EXT  VARCHAR2(10)   DEFAULT '' ,
    CUR_GP      NUMBER(14, 4)  DEFAULT 0  NOT NULL,
    MAX_GP      NUMBER(14, 4)  DEFAULT 0  NOT NULL,
    UPDATE_DATE DATE           DEFAULT SYSDATE,
    CONSTRAINT PK_TBOT_POINT_NEW_RANK PRIMARY KEY (USER_NAME)
);
