package my.prac.core.game.dto;

import java.io.Serializable;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class AttackCalc {
	public String userName;
	public String roomName;
	public int lv;
	public int expCur;
	public int expNext;
	public int hpCur;
	public int hpMax;
	public int hpRegen;
	public int atkDmg; 
	public int monDmg; 
	public int atkMin;
	public int atkMax;
	public String patternMsg;
	public int baseAtk; 
	public double critMultiplier;
	public double critRate; // %
	public double critDmg;  // %
	public int targetMon;
	public boolean jobSkillUsed;
}
