package my.prac.core.game.dto;

import java.io.Serializable;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BagLog {
	private String userName;
	private String roomName;
	private java.sql.Timestamp insertDate;

	public String getUserName() {
		return userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getRoomName() {
		return roomName;
	}

	public void setRoomName(String roomName) {
		this.roomName = roomName;
	}

	public java.sql.Timestamp getInsertDate() {
		return insertDate;
	}

	public void setInsertDate(java.sql.Timestamp insertDate) {
		this.insertDate = insertDate;
	}
}
