package my.prac.core.game.dto;

import java.util.Date;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class BagRewardLog {
	private String userName;
    private String roomName;
    private String gain;       // "1000 sp" 또는 "꿈의대검"
    private String gainType;   // "BAG_OPEN_91", "BAG_OPEN_92", "HELL_BOX" 등
    private Date insertDate;

    public String getUserName() { return userName; }
    public void setUserName(String userName) { this.userName = userName; }

    public String getRoomName() { return roomName; }
    public void setRoomName(String roomName) { this.roomName = roomName; }

    public String getGain() { return gain; }
    public void setGain(String gain) { this.gain = gain; }

    public String getGainType() { return gainType; }
    public void setGainType(String gainType) { this.gainType = gainType; }

    public Date getInsertDate() { return insertDate; }
    public void setInsertDate(Date insertDate) { this.insertDate = insertDate; }
	
	
}
