package my.prac.core.game.dto;


/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public class DamageOutcome {
	public AttackCalc calc;
	public Flags flags;
	public boolean willKill;  // 이번 공격으로 몹 죽는지
	public String extraMsg; // 패턴/직업 스킬 메시지
}