package my.prac.core.game.dto;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class EquipCategory {
	public String name;
    public int max;
    public int[][] ranges;
    public String[] aliases;

    public EquipCategory(String name, int max, int[][] ranges, String... aliases) {
        this.name = name;
        this.max = max;
        this.ranges = ranges;
        this.aliases = aliases;
    }

    public boolean contains(int itemId) {
        for (int[] r : ranges) {
            if (itemId > r[0] && itemId <= r[1]) {
                return true;
            }
        }
        return false;
    }

    public boolean matchAlias(String s) {
        for (String a : aliases) {
            if (a.equals(s)) return true;
        }
        return false;
    }

    public int[] firstRange() {
        return ranges[0];
    }
}