package my.prac.core.game.dto;

import java.io.Serializable;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class OngoingBattle {
	public int monNo;
    public int totalDealtDmg;
    public Integer beforeJobSkillYn;

    // 진행 중 전투(now_yn=1) 묶음에서 ‘가장 최근’ lucky 상태
    public Integer luckyYn; // 0/1, null 가능
    

    public OngoingBattle setMonNo(int v){ this.monNo=v; return this; }
    public OngoingBattle setTotalDealtDmg(int v){ this.totalDealtDmg=v; return this; }
    public OngoingBattle setLuckyYn(Integer v){ this.luckyYn=v; return this; }
    public OngoingBattle setBeforeJobSkillYn(int v){ this.beforeJobSkillYn=v; return this; }
}