package my.prac.core.game.dto;

import java.io.Serializable;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class OngoingBattle {
	public int monNo;          // TARGET_MON_LV = MON_NO
	public int totalDealtDmg;  // NOW_YN=1 묶음에서 누적 가한 피해 합계
}