package my.prac.core.game.dto;

import java.sql.Timestamp;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class SpecialBuffResult {
	public boolean started;     // 이번에 새로 발동했는지
    public String startMsg;     // 발동 메시지
    public String runningMsg;   // 진행중 메시지
}