package my.prac.core.game.dto;

import java.util.HashMap;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class SpecialBuffOption {
	public int weight;
	public String flagCode;
	public String effectType;

    public SpecialBuffOption(int weight, String flagCode, String effectType) {
        this.weight = weight;
        this.flagCode = flagCode;
        this.effectType = effectType;
    }
}