package my.prac.core.game.dto;

import java.sql.Timestamp;

/**
 * 사용자 모델 클래스.
 * 
 * @author generated by ERMaster
 * @version $Id$
 */
public  class User {
	public String userName;
	public String roomName;
	public int lv;
	public int expCur;
	public int expNext;
	public int hpCur;
	public int hpMax;
	public int hpRegen;
	public int atkMin;
	public int atkMax;
	public int critRate; // %
	public int critDmg;  // %
	public int targetMon;
	public java.sql.Timestamp insertDate; // ⬅️ fallback용
	public String job;
	public Timestamp jobChangeDate;
	public long totalSp; 
	public String hunterGrade;
}