-- 매크로 탐지 테이블
-- DB: AWS_NEW (dev-apc.com:2010 / XE)
CREATE TABLE TBOT_MACRO_DETECT (
    USER_NAME  VARCHAR2(100) NOT NULL,
    CODE       VARCHAR2(20)  NOT NULL,
    LOCKED_YN  CHAR(1)       DEFAULT '1' NOT NULL,
    LOCK_DATE  DATE          DEFAULT SYSDATE NOT NULL,
    CONSTRAINT PK_TBOT_MACRO_DETECT PRIMARY KEY (USER_NAME)
);
